services:
  - type: web
    name: brainai
    plan: free
    env: python
    buildCommand: bash render_build.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONUNBUFFERED
        value: "1"
